apiVersion: apps/v1
kind: Deployment
metadata:
  name: vendor-heavy-2
  labels:
    app: plugin-hub
    component: vendor
    tier: heavy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plugin-hub
      component: vendor
      tier: heavy
      deployment: heavy-2
  template:
    metadata:
      labels:
        app: plugin-hub
        component: vendor
        tier: heavy
        deployment: heavy-2
    spec:
      containers:
      - name: vendor
        image: ghcr.io/shawnlin0125/plugin-hub-heavy-2:latest
        ports:
        - containerPort: 8000
        env:
        - name: LOAD_PLUGINS
          value: "kktix"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: routing-config
          mountPath: /etc/plugin-hub
          readOnly: true
      volumes:
      - name: routing-config
        configMap:
          name: vendor-routing
